type EffectTargetType = "HARD_CONSTRAINT" | "PERSONALITY_TRAIT" | "VEHICLE_PREFERENCE";

type RuleOperator = "EQ" | "NEQ" | "GT" | "GTE" | "LT" | "LTE";

type ConstraintRule = {
  targetType: EffectTargetType;
  targetKey: string;
  traitOperator: RuleOperator;
  traitThreshold: number;
};

function weight(targetType: EffectTargetType, targetKey: string, value: number) {
  return { targetType, targetKey, weight: value } as const;
}

function constraint(targetKey: string, traitOperator: RuleOperator, traitThreshold: number) {
  return {
    targetType: "HARD_CONSTRAINT" as const,
    targetKey,
    traitOperator,
    traitThreshold,
  };
}

function vehicle(input: {
  slug: string;
  brand: string;
  series: string;
  modelName: string;
  priceMin: number;
  priceMax: number;
  energyType: string;
  bodyType: string;
  summary: string;
  recommendation: string;
  tags: readonly string[];
  traitWeights: ReadonlyArray<{ targetType: EffectTargetType; targetKey: string; weight: number }>;
  constraintRules: ReadonlyArray<ConstraintRule>;
}) {
  return {
    ...input,
    modelName: "",
  };
}

export const vehicles = [
  vehicle({
    slug: "byd-song-plus-dmi",
    brand: "比亚迪",
    series: "宋 PLUS",
    modelName: "DM-i",
    priceMin: 129800,
    priceMax: 189800,
    energyType: "PHEV",
    bodyType: "SUV",
    summary: "偏家庭导向、综合成本友好的插混 SUV",
    recommendation: "适合偏稳健务实、重视空间与长期成本的家庭用户",
    tags: ["family", "value"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "comfort_space", 9),
      weight("VEHICLE_PREFERENCE", "family_fit", 10),
      weight("VEHICLE_PREFERENCE", "running_cost", 9),
      weight("PERSONALITY_TRAIT", "stability_preference", 7),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 2),
      constraint("energy_acceptance_phev", "GTE", 2),
      constraint("family_size", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "tesla-model-3",
    brand: "特斯拉",
    series: "Model 3",
    modelName: "后轮驱动版",
    priceMin: 231900,
    priceMax: 285900,
    energyType: "EV",
    bodyType: "Sedan",
    summary: "强调科技体验和驾驶感受的纯电轿车",
    recommendation: "适合愿意尝鲜、补能条件较好且在意科技感的人",
    tags: ["technology", "expression"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "smart_features", 9),
      weight("VEHICLE_PREFERENCE", "driving_engagement", 8),
      weight("VEHICLE_PREFERENCE", "brand_expression", 8),
      weight("PERSONALITY_TRAIT", "novelty_seeking", 8),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("charging_access", "GTE", 3),
      constraint("energy_acceptance_ev", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "toyota-corolla-hybrid",
    brand: "丰田",
    series: "卡罗拉",
    modelName: "双擎",
    priceMin: 119800,
    priceMax: 155800,
    energyType: "HEV",
    bodyType: "Sedan",
    summary: "稳定、省心、适合高频通勤的混动家轿",
    recommendation: "适合重视可靠性、通勤成本和长期持有体验的用户",
    tags: ["commute", "reliable"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "daily_reliability", 10),
      weight("VEHICLE_PREFERENCE", "running_cost", 9),
      weight("VEHICLE_PREFERENCE", "simplicity_reliability", 8),
      weight("PERSONALITY_TRAIT", "cost_control", 8),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 2),
      constraint("monthly_payment_sensitivity", "GTE", 2),
      constraint("urban_commute_density", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "xiaomi-su7",
    brand: "小米",
    series: "SU7",
    modelName: "标准版",
    priceMin: 215900,
    priceMax: 299900,
    energyType: "EV",
    bodyType: "Sedan",
    summary: "智能座舱和新鲜感都很强的纯电轿跑",
    recommendation: "适合愿意接受新技术、偏爱设计和智能交互的人群",
    tags: ["technology", "expression"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "smart_features", 10),
      weight("VEHICLE_PREFERENCE", "driving_engagement", 8),
      weight("VEHICLE_PREFERENCE", "design_presence", 8),
      weight("VEHICLE_PREFERENCE", "brand_expression", 8),
      weight("PERSONALITY_TRAIT", "novelty_seeking", 8),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("charging_access", "GTE", 3),
      constraint("energy_acceptance_ev", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "li-auto-l6",
    brand: "理想",
    series: "L6",
    modelName: "Pro",
    priceMin: 249800,
    priceMax: 279800,
    energyType: "EREV",
    bodyType: "SUV",
    summary: "家庭舒适、空间表现和智能辅助都比较均衡的增程 SUV",
    recommendation: "适合家庭成员较多、希望空间和补能便利兼得的用户",
    tags: ["family", "technology"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "comfort_space", 9),
      weight("VEHICLE_PREFERENCE", "family_fit", 10),
      weight("VEHICLE_PREFERENCE", "smart_features", 7),
      weight("PERSONALITY_TRAIT", "stability_preference", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("family_size", "GTE", 3),
      constraint("energy_acceptance_phev", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "mazda-cx-5",
    brand: "马自达",
    series: "CX-5",
    modelName: "2.5L",
    priceMin: 175800,
    priceMax: 215800,
    energyType: "ICE",
    bodyType: "SUV",
    summary: "强调驾驶反馈与机械质感的燃油 SUV",
    recommendation: "适合仍然看重操控手感、同时能接受燃油方案的人",
    tags: ["driving", "balanced"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "driving_engagement", 10),
      weight("VEHICLE_PREFERENCE", "simplicity_reliability", 7),
      weight("VEHICLE_PREFERENCE", "design_presence", 6),
      weight("PERSONALITY_TRAIT", "control_preference", 7),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 3),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("parking_constraint", "LTE", 4),
    ],
  }),
  vehicle({
    slug: "geely-xingyue-l",
    brand: "吉利",
    series: "星越 L",
    modelName: "智擎",
    priceMin: 157700,
    priceMax: 187700,
    energyType: "HEV",
    bodyType: "SUV",
    summary: "空间配置均衡、性价比较强的家用 SUV",
    recommendation: "适合预算理性、家用场景明确、希望配置完整的用户",
    tags: ["family", "value"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "family_fit", 9),
      weight("VEHICLE_PREFERENCE", "comfort_space", 8),
      weight("VEHICLE_PREFERENCE", "running_cost", 7),
      weight("PERSONALITY_TRAIT", "cost_control", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 3),
      constraint("family_size", "GTE", 2),
      constraint("cargo_space_need", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "honda-cr-v-ehev",
    brand: "本田",
    series: "CR-V",
    modelName: "e:HEV",
    priceMin: 199900,
    priceMax: 264900,
    energyType: "HEV",
    bodyType: "SUV",
    summary: "可靠、舒适、通勤和家庭场景都稳的混动 SUV",
    recommendation: "适合既有家庭需求又不想承担补能焦虑的用户",
    tags: ["family", "reliable"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "daily_reliability", 10),
      weight("VEHICLE_PREFERENCE", "family_fit", 8),
      weight("VEHICLE_PREFERENCE", "comfort_space", 8),
      weight("PERSONALITY_TRAIT", "stability_preference", 7),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("family_size", "GTE", 2),
      constraint("has_elder_passengers", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "zeekr-007",
    brand: "极氪",
    series: "007",
    modelName: "后驱增强版",
    priceMin: 209900,
    priceMax: 299900,
    energyType: "EV",
    bodyType: "Sedan",
    summary: "设计锋利、性能和智能体验兼顾的纯电轿车",
    recommendation: "适合看重性能表达、科技感和外观张力的人",
    tags: ["technology", "driving"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "design_presence", 9),
      weight("VEHICLE_PREFERENCE", "driving_engagement", 8),
      weight("VEHICLE_PREFERENCE", "smart_features", 8),
      weight("PERSONALITY_TRAIT", "expression_drive", 7),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("charging_access", "GTE", 3),
      constraint("energy_acceptance_ev", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "nissan-sylphy",
    brand: "日产",
    series: "轩逸",
    modelName: "经典舒适版",
    priceMin: 108600,
    priceMax: 139900,
    energyType: "ICE",
    bodyType: "Sedan",
    summary: "舒适好开、预算友好、适合日常代步的家轿",
    recommendation: "适合预算敏感、只想稳定代步的用户",
    tags: ["commute", "value"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "comfort_space", 7),
      weight("VEHICLE_PREFERENCE", "running_cost", 8),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 8),
      weight("PERSONALITY_TRAIT", "stability_preference", 6),
      weight("VEHICLE_PREFERENCE", "smart_features", 1),
      weight("VEHICLE_PREFERENCE", "driving_engagement", 1),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 1),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("monthly_payment_sensitivity", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "volkswagen-tiguan-l",
    brand: "大众",
    series: "途观 L",
    modelName: "330TSI",
    priceMin: 186800,
    priceMax: 246800,
    energyType: "ICE",
    bodyType: "SUV",
    summary: "空间和保有量都较平衡的传统家用 SUV",
    recommendation: "适合务实家用、在意品牌成熟度和大空间的人",
    tags: ["family", "reliable"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "family_fit", 8),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 7),
      weight("VEHICLE_PREFERENCE", "comfort_space", 7),
      weight("PERSONALITY_TRAIT", "planning_bias", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 3),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("family_size", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "nio-es6",
    brand: "蔚来",
    series: "ES6",
    modelName: "75kWh",
    priceMin: 338000,
    priceMax: 396000,
    energyType: "EV",
    bodyType: "SUV",
    summary: "高智能体验与中型 SUV 空间兼顾的纯电方案",
    recommendation: "适合预算充足、补能条件好、愿意为体验买单的用户",
    tags: ["technology", "family"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "smart_features", 9),
      weight("VEHICLE_PREFERENCE", "comfort_space", 8),
      weight("VEHICLE_PREFERENCE", "family_fit", 7),
      weight("PERSONALITY_TRAIT", "novelty_seeking", 7),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 5),
      constraint("charging_access", "GTE", 3),
      constraint("energy_acceptance_ev", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "aito-m7",
    brand: "问界",
    series: "M7",
    modelName: "Plus",
    priceMin: 249800,
    priceMax: 329800,
    energyType: "EREV",
    bodyType: "SUV",
    summary: "偏家庭舒适和智能便利的大空间增程 SUV",
    recommendation: "适合多人口家庭、长短途混合使用、又在意智能体验的用户",
    tags: ["family", "technology"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "family_fit", 10),
      weight("VEHICLE_PREFERENCE", "comfort_space", 9),
      weight("VEHICLE_PREFERENCE", "smart_features", 8),
      weight("PERSONALITY_TRAIT", "stability_preference", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("family_size", "GTE", 3),
      constraint("energy_acceptance_phev", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "toyota-rav4-hybrid",
    brand: "丰田",
    series: "RAV4",
    modelName: "双擎",
    priceMin: 225800,
    priceMax: 296800,
    energyType: "HEV",
    bodyType: "SUV",
    summary: "稳定耐用、兼顾城市与长途的混动 SUV",
    recommendation: "适合看重可靠性、保值和多场景通用性的用户",
    tags: ["reliable", "family"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "daily_reliability", 10),
      weight("VEHICLE_PREFERENCE", "family_fit", 7),
      weight("VEHICLE_PREFERENCE", "running_cost", 7),
      weight("PERSONALITY_TRAIT", "planning_bias", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("long_distance_frequency", "GTE", 2),
      constraint("resale_sensitivity", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "honda-fit",
    brand: "本田",
    series: "飞度",
    modelName: "潮跑版",
    priceMin: 86800,
    priceMax: 108800,
    energyType: "ICE",
    bodyType: "Hatchback",
    summary: "停车友好、经济灵活的小型代步车",
    recommendation: "适合预算有限、停车压力大、以城市代步为主的用户",
    tags: ["commute", "value"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "running_cost", 8),
      weight("VEHICLE_PREFERENCE", "driving_engagement", 6),
      weight("VEHICLE_PREFERENCE", "simplicity_reliability", 8),
      weight("PERSONALITY_TRAIT", "cost_control", 7),
      weight("VEHICLE_PREFERENCE", "smart_features", 1),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 1),
      constraint("parking_constraint", "GTE", 3),
      constraint("energy_acceptance_ice", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "mercedes-c-class",
    brand: "奔驰",
    series: "C 级",
    modelName: "C 260 L",
    priceMin: 332300,
    priceMax: 379000,
    energyType: "ICE",
    bodyType: "Sedan",
    summary: "品牌认知和豪华氛围更突出的中型轿车",
    recommendation: "适合预算较高、重视品牌感和体面表达的用户",
    tags: ["premium", "expression"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "brand_expression", 10),
      weight("VEHICLE_PREFERENCE", "design_presence", 8),
      weight("VEHICLE_PREFERENCE", "comfort_space", 6),
      weight("PERSONALITY_TRAIT", "expression_drive", 7),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 5),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("monthly_payment_sensitivity", "LTE", 3),
    ],
  }),
  vehicle({
    slug: "wuling-bingo-plus",
    brand: "五菱",
    series: "缤果 Plus",
    modelName: "510km",
    priceMin: 89800,
    priceMax: 98800,
    energyType: "EV",
    bodyType: "Hatchback",
    summary: "预算友好、通勤导向的小型纯电车",
    recommendation: "适合城市短途通勤、预算有限但有补能条件的用户",
    tags: ["commute", "ev"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "running_cost", 9),
      weight("VEHICLE_PREFERENCE", "smart_features", 5),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 6),
      weight("PERSONALITY_TRAIT", "cost_control", 8),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 1),
      constraint("charging_access", "GTE", 3),
      constraint("energy_acceptance_ev", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "byd-seagull",
    brand: "比亚迪",
    series: "海鸥",
    modelName: "飞翔版",
    priceMin: 85800,
    priceMax: 95800,
    energyType: "EV",
    bodyType: "Hatchback",
    summary: "高频城市通勤导向的入门纯电小车",
    recommendation: "适合重视停车灵活度和日常通勤成本的用户",
    tags: ["commute", "ev"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "running_cost", 9),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 6),
      weight("VEHICLE_PREFERENCE", "smart_features", 5),
      weight("PERSONALITY_TRAIT", "cost_control", 8),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 1),
      constraint("charging_access", "GTE", 3),
      constraint("parking_constraint", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "tank-300",
    brand: "坦克",
    series: "300",
    modelName: "城市版",
    priceMin: 199800,
    priceMax: 309800,
    energyType: "ICE",
    bodyType: "SUV",
    summary: "风格鲜明、通过性和个性标签都比较强的硬派 SUV",
    recommendation: "适合看重造型表达和周末户外场景的用户",
    tags: ["expression", "outdoor"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "design_presence", 9),
      weight("VEHICLE_PREFERENCE", "brand_expression", 8),
      weight("VEHICLE_PREFERENCE", "driving_engagement", 6),
      weight("PERSONALITY_TRAIT", "expression_drive", 7),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("parking_constraint", "LTE", 3),
      constraint("energy_acceptance_ice", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "bmw-i3-edrive35l",
    brand: "宝马",
    series: "i3",
    modelName: "eDrive35L",
    priceMin: 353900,
    priceMax: 413900,
    energyType: "EV",
    bodyType: "Sedan",
    summary: "兼顾品牌认知、驾控和纯电体验的豪华轿车",
    recommendation: "适合预算充足、同时在意品牌和驾控的纯电用户",
    tags: ["premium", "driving"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "driving_engagement", 8),
      weight("VEHICLE_PREFERENCE", "brand_expression", 9),
      weight("VEHICLE_PREFERENCE", "smart_features", 7),
      weight("PERSONALITY_TRAIT", "control_preference", 7),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 5),
      constraint("charging_access", "GTE", 3),
      constraint("energy_acceptance_ev", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "audi-a6l",
    brand: "奥迪",
    series: "A6L",
    modelName: "40 TFSI",
    priceMin: 427900,
    priceMax: 503900,
    energyType: "ICE",
    bodyType: "Sedan",
    summary: "商务稳重、空间和高级感都比较突出的中大型轿车",
    recommendation: "适合预算高、重视品牌稳重感和后排体验的用户",
    tags: ["premium", "comfort"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "comfort_space", 8),
      weight("VEHICLE_PREFERENCE", "brand_expression", 9),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 6),
      weight("PERSONALITY_TRAIT", "stability_preference", 7),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 5),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("monthly_payment_sensitivity", "LTE", 2),
    ],
  }),
  vehicle({
    slug: "toyota-sienna",
    brand: "丰田",
    series: "赛那",
    modelName: "2.5L 混动",
    priceMin: 309800,
    priceMax: 411800,
    energyType: "HEV",
    bodyType: "MPV",
    summary: "多人家庭长途舒适和上下车便利都很突出的 MPV",
    recommendation: "适合孩子和老人同乘较多、对空间与舒适有刚需的家庭",
    tags: ["family", "comfort"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "family_fit", 10),
      weight("VEHICLE_PREFERENCE", "comfort_space", 10),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 7),
      weight("PERSONALITY_TRAIT", "stability_preference", 7),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 5),
      constraint("family_size", "GTE", 4),
      constraint("has_children", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "buick-gl8-phev",
    brand: "别克",
    series: "GL8",
    modelName: "陆尊 PHEV",
    priceMin: 359900,
    priceMax: 419900,
    energyType: "PHEV",
    bodyType: "MPV",
    summary: "商务和家庭兼容度都很高的大空间插混 MPV",
    recommendation: "适合多成员家庭或高频接待场景，且愿意接受插混方案的用户",
    tags: ["family", "premium"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "family_fit", 10),
      weight("VEHICLE_PREFERENCE", "comfort_space", 10),
      weight("VEHICLE_PREFERENCE", "smart_features", 6),
      weight("PERSONALITY_TRAIT", "planning_bias", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 5),
      constraint("family_size", "GTE", 4),
      constraint("energy_acceptance_phev", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "volkswagen-passat-pro",
    brand: "大众",
    series: "帕萨特 Pro",
    modelName: "380TSI",
    priceMin: 189900,
    priceMax: 249900,
    energyType: "ICE",
    bodyType: "Sedan",
    summary: "空间、品牌认知和高速稳定性都比较均衡的中型轿车",
    recommendation: "适合重视通勤质感、长途稳定和品牌成熟度的用户",
    tags: ["commute", "reliable"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "daily_reliability", 8),
      weight("VEHICLE_PREFERENCE", "comfort_space", 7),
      weight("VEHICLE_PREFERENCE", "brand_expression", 6),
      weight("PERSONALITY_TRAIT", "planning_bias", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 3),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("intercity_highway_usage", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "volkswagen-tiguan-l-pro",
    brand: "大众",
    series: "途观 L Pro",
    modelName: "330TSI",
    priceMin: 236800,
    priceMax: 266800,
    energyType: "ICE",
    bodyType: "SUV",
    summary: "大空间和合资成熟度兼顾的家用 SUV",
    recommendation: "适合家庭成员较多、想要空间和成熟度兼顾的用户",
    tags: ["family", "reliable"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "family_fit", 8),
      weight("VEHICLE_PREFERENCE", "comfort_space", 8),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 7),
      weight("PERSONALITY_TRAIT", "stability_preference", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("family_size", "GTE", 2),
      constraint("energy_acceptance_ice", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "volkswagen-id3",
    brand: "大众",
    series: "ID.3",
    modelName: "聪明款",
    priceMin: 129888,
    priceMax: 147888,
    energyType: "EV",
    bodyType: "Hatchback",
    summary: "预算相对友好的合资纯电两厢车",
    recommendation: "适合有充电条件、重视城市通勤和品牌成熟度的纯电用户",
    tags: ["commute", "ev"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "running_cost", 8),
      weight("VEHICLE_PREFERENCE", "smart_features", 6),
      weight("VEHICLE_PREFERENCE", "driving_engagement", 5),
      weight("PERSONALITY_TRAIT", "novelty_seeking", 5),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 2),
      constraint("charging_access", "GTE", 3),
      constraint("energy_acceptance_ev", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "volkswagen-id4-x",
    brand: "大众",
    series: "ID.4 X",
    modelName: "纯净长续航版",
    priceMin: 159888,
    priceMax: 215888,
    energyType: "EV",
    bodyType: "SUV",
    summary: "空间和纯电体验更均衡的合资纯电 SUV",
    recommendation: "适合有补能条件、想要家用纯电 SUV 的用户",
    tags: ["family", "ev"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "comfort_space", 8),
      weight("VEHICLE_PREFERENCE", "smart_features", 6),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 8),
      weight("PERSONALITY_TRAIT", "stability_preference", 5),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 3),
      constraint("charging_access", "GTE", 3),
      constraint("energy_acceptance_ev", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "volkswagen-id4-crozz",
    brand: "大众",
    series: "ID.4 CROZZ",
    modelName: "长续航 Lite Pro",
    priceMin: 195900,
    priceMax: 287300,
    energyType: "EV",
    bodyType: "SUV",
    summary: "偏均衡取向的一汽大众纯电 SUV",
    recommendation: "适合想要合资纯电平台、空间和稳定性兼顾的用户",
    tags: ["family", "ev"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "comfort_space", 8),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 8),
      weight("VEHICLE_PREFERENCE", "smart_features", 6),
      weight("PERSONALITY_TRAIT", "planning_bias", 5),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 3),
      constraint("charging_access", "GTE", 3),
      constraint("energy_acceptance_ev", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "volkswagen-golf",
    brand: "大众",
    series: "高尔夫",
    modelName: "300TSI",
    priceMin: 149800,
    priceMax: 229800,
    energyType: "ICE",
    bodyType: "Hatchback",
    summary: "更强调灵活操控和品牌经典感的小钢炮取向两厢车",
    recommendation: "适合预算中等、喜欢驾驶反馈和紧凑车身的用户",
    tags: ["driving", "balanced"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "driving_engagement", 8),
      weight("VEHICLE_PREFERENCE", "design_presence", 5),
      weight("VEHICLE_PREFERENCE", "brand_expression", 5),
      weight("PERSONALITY_TRAIT", "control_preference", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 3),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("parking_constraint", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "volkswagen-sagitar",
    brand: "大众",
    series: "速腾",
    modelName: "300TSI",
    priceMin: 127900,
    priceMax: 172900,
    energyType: "ICE",
    bodyType: "Sedan",
    summary: "偏主流家用通勤取向的紧凑级轿车",
    recommendation: "适合预算克制、希望空间和通勤体验均衡的用户",
    tags: ["commute", "value"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "daily_reliability", 8),
      weight("VEHICLE_PREFERENCE", "comfort_space", 6),
      weight("VEHICLE_PREFERENCE", "running_cost", 6),
      weight("PERSONALITY_TRAIT", "stability_preference", 5),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 2),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("monthly_payment_sensitivity", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "volkswagen-bora",
    brand: "大众",
    series: "宝来",
    modelName: "200TSI",
    priceMin: 112900,
    priceMax: 139900,
    energyType: "ICE",
    bodyType: "Sedan",
    summary: "预算门槛更低的主流家用轿车",
    recommendation: "适合看重预算和合资基础口碑的用户",
    tags: ["commute", "value"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "running_cost", 8),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 6),
      weight("VEHICLE_PREFERENCE", "comfort_space", 5),
      weight("PERSONALITY_TRAIT", "cost_control", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 2),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("monthly_payment_sensitivity", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "volkswagen-lavida-xinrui",
    brand: "大众",
    series: "朗逸新锐",
    modelName: "1.5L",
    priceMin: 79999,
    priceMax: 108999,
    energyType: "ICE",
    bodyType: "Sedan",
    summary: "价格门槛更低的德系家用入门轿车",
    recommendation: "适合预算敏感、优先满足代步需求的用户",
    tags: ["commute", "value"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "running_cost", 8),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 6),
      weight("VEHICLE_PREFERENCE", "smart_features", 1),
      weight("PERSONALITY_TRAIT", "cost_control", 7),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 1),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("monthly_payment_sensitivity", "GTE", 4),
    ],
  }),
  vehicle({
    slug: "volkswagen-teramont-pro",
    brand: "大众",
    series: "途昂 Pro",
    modelName: "380TSI",
    priceMin: 309900,
    priceMax: 359900,
    energyType: "ICE",
    bodyType: "SUV",
    summary: "更偏大空间和多人出行取向的中大型 SUV",
    recommendation: "适合成员多、装载多、想要大车安全感的家庭用户",
    tags: ["family", "comfort"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "family_fit", 9),
      weight("VEHICLE_PREFERENCE", "comfort_space", 9),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 6),
      weight("PERSONALITY_TRAIT", "stability_preference", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 5),
      constraint("family_size", "GTE", 3),
      constraint("cargo_space_need", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "volkswagen-viloran",
    brand: "大众",
    series: "威然",
    modelName: "380TSI",
    priceMin: 289800,
    priceMax: 402800,
    energyType: "ICE",
    bodyType: "MPV",
    summary: "商务和家庭兼顾的大空间 MPV",
    recommendation: "适合多人乘坐频繁、看重第二排舒适的用户",
    tags: ["family", "comfort"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "family_fit", 9),
      weight("VEHICLE_PREFERENCE", "comfort_space", 10),
      weight("VEHICLE_PREFERENCE", "brand_expression", 5),
      weight("PERSONALITY_TRAIT", "planning_bias", 5),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 5),
      constraint("family_size", "GTE", 4),
      constraint("has_elder_passengers", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "volkswagen-touran-l",
    brand: "大众",
    series: "途安 L",
    modelName: "280TSI",
    priceMin: 159800,
    priceMax: 199800,
    energyType: "ICE",
    bodyType: "MPV",
    summary: "更务实的小型 MPV 家用方案",
    recommendation: "适合预算有限但又确实需要多人空间的家庭",
    tags: ["family", "value"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "family_fit", 8),
      weight("VEHICLE_PREFERENCE", "comfort_space", 8),
      weight("VEHICLE_PREFERENCE", "running_cost", 6),
      weight("PERSONALITY_TRAIT", "cost_control", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 3),
      constraint("family_size", "GTE", 3),
      constraint("energy_acceptance_ice", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "honda-accord",
    brand: "本田",
    series: "雅阁",
    modelName: "e:PHEV",
    priceMin: 225800,
    priceMax: 258800,
    energyType: "PHEV",
    bodyType: "Sedan",
    summary: "空间、品牌和插混平衡感都较好的中型轿车",
    recommendation: "适合通勤和家用兼顾、又愿意接受插混的用户",
    tags: ["commute", "technology"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "comfort_space", 8),
      weight("VEHICLE_PREFERENCE", "running_cost", 7),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 8),
      weight("PERSONALITY_TRAIT", "planning_bias", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("energy_acceptance_phev", "GTE", 2),
      constraint("intercity_highway_usage", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "honda-breeze-ehev",
    brand: "本田",
    series: "皓影",
    modelName: "e:HEV",
    priceMin: 209800,
    priceMax: 269900,
    energyType: "HEV",
    bodyType: "SUV",
    summary: "空间、舒适和混动省心度都比较均衡的家用 SUV",
    recommendation: "适合家庭导向、偏稳妥的混动 SUV 用户",
    tags: ["family", "reliable"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "family_fit", 8),
      weight("VEHICLE_PREFERENCE", "comfort_space", 8),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 8),
      weight("PERSONALITY_TRAIT", "stability_preference", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("family_size", "GTE", 2),
      constraint("has_children", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "honda-integra",
    brand: "本田",
    series: "型格",
    modelName: "e:HEV",
    priceMin: 159900,
    priceMax: 186900,
    energyType: "HEV",
    bodyType: "Sedan",
    summary: "年轻化设计和一定驾驶乐趣兼顾的紧凑级轿车",
    recommendation: "适合预算中等、想要一些操控感和设计感的用户",
    tags: ["driving", "balanced"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "driving_engagement", 8),
      weight("VEHICLE_PREFERENCE", "design_presence", 5),
      weight("VEHICLE_PREFERENCE", "running_cost", 6),
      weight("PERSONALITY_TRAIT", "control_preference", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 3),
      constraint("monthly_payment_sensitivity", "GTE", 2),
      constraint("energy_acceptance_ice", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "honda-ens1-p7",
    brand: "本田",
    series: "P7",
    modelName: "后驱版",
    priceMin: 199900,
    priceMax: 249900,
    energyType: "EV",
    bodyType: "SUV",
    summary: "本田纯电序列里更偏科技和纯电体验的 SUV",
    recommendation: "适合有补能条件、希望纯电但又偏向传统品牌的人",
    tags: ["technology", "ev"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "smart_features", 8),
      weight("VEHICLE_PREFERENCE", "driving_engagement", 6),
      weight("VEHICLE_PREFERENCE", "design_presence", 5),
      weight("PERSONALITY_TRAIT", "novelty_seeking", 5),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("charging_access", "GTE", 3),
      constraint("energy_acceptance_ev", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "honda-vezel",
    brand: "本田",
    series: "缤智",
    modelName: "1.5L",
    priceMin: 132900,
    priceMax: 152900,
    energyType: "ICE",
    bodyType: "SUV",
    summary: "城市通勤和灵活停车友好的小型 SUV",
    recommendation: "适合预算适中、以城市代步为主的年轻用户",
    tags: ["commute", "value"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "running_cost", 8),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 6),
      weight("VEHICLE_PREFERENCE", "driving_engagement", 4),
      weight("PERSONALITY_TRAIT", "cost_control", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 2),
      constraint("parking_constraint", "GTE", 2),
      constraint("energy_acceptance_ice", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "honda-zrv",
    brand: "本田",
    series: "致在",
    modelName: "e:HEV",
    priceMin: 179900,
    priceMax: 229900,
    energyType: "HEV",
    bodyType: "SUV",
    summary: "体型适中、风格年轻、兼顾家用和驾驶感的小型 SUV",
    recommendation: "适合想要城市灵活性和一定驾驶感平衡的用户",
    tags: ["balanced", "driving"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "driving_engagement", 8),
      weight("VEHICLE_PREFERENCE", "design_presence", 5),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 7),
      weight("PERSONALITY_TRAIT", "control_preference", 5),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 3),
      constraint("energy_acceptance_ice", "GTE", 2),
      constraint("parking_constraint", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "honda-odyssey-ehev",
    brand: "本田",
    series: "奥德赛",
    modelName: "e:HEV",
    priceMin: 235800,
    priceMax: 439800,
    energyType: "HEV",
    bodyType: "MPV",
    summary: "本田家用 MPV 里更成熟经典的多人舒适方案",
    recommendation: "适合多人家庭、老人孩子同乘频繁的用户",
    tags: ["family", "comfort"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "family_fit", 9),
      weight("VEHICLE_PREFERENCE", "comfort_space", 10),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 7),
      weight("PERSONALITY_TRAIT", "stability_preference", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("family_size", "GTE", 4),
      constraint("has_elder_passengers", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "honda-avancier",
    brand: "本田",
    series: "冠道",
    modelName: "370TURBO",
    priceMin: 239800,
    priceMax: 329800,
    energyType: "ICE",
    bodyType: "SUV",
    summary: "偏大五座舒适和气场表达的中型 SUV",
    recommendation: "适合重视后排空间、品牌和燃油方案成熟度的用户",
    tags: ["comfort", "expression"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "comfort_space", 8),
      weight("VEHICLE_PREFERENCE", "brand_expression", 6),
      weight("VEHICLE_PREFERENCE", "driving_engagement", 5),
      weight("PERSONALITY_TRAIT", "expression_drive", 5),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("family_size", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "honda-ens2",
    brand: "本田",
    series: "极湃 2",
    modelName: "e:NP2",
    priceMin: 159800,
    priceMax: 199800,
    energyType: "EV",
    bodyType: "SUV",
    summary: "本田纯电阵列里更偏家用的紧凑 SUV",
    recommendation: "适合有补能条件、预算中等、希望纯电家用的用户",
    tags: ["family", "ev"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "smart_features", 8),
      weight("VEHICLE_PREFERENCE", "comfort_space", 6),
      weight("VEHICLE_PREFERENCE", "running_cost", 7),
      weight("PERSONALITY_TRAIT", "novelty_seeking", 4),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 3),
      constraint("charging_access", "GTE", 3),
      constraint("energy_acceptance_ev", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "lynkco-03-plus",
    brand: "领克",
    series: "03+",
    modelName: "驭风版",
    priceMin: 195800,
    priceMax: 258800,
    energyType: "ICE",
    bodyType: "Sedan",
    summary: "领克体系里更鲜明的性能表达车型",
    recommendation: "适合明确追求动力、操控和个性表达的用户",
    tags: ["driving", "expression"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "driving_engagement", 10),
      weight("VEHICLE_PREFERENCE", "design_presence", 7),
      weight("VEHICLE_PREFERENCE", "brand_expression", 8),
      weight("PERSONALITY_TRAIT", "expression_drive", 7),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("parking_constraint", "LTE", 4),
    ],
  }),
  vehicle({
    slug: "lynkco-08-emp",
    brand: "领克",
    series: "08 EM-P",
    modelName: "四驱版",
    priceMin: 195800,
    priceMax: 288000,
    energyType: "PHEV",
    bodyType: "SUV",
    summary: "领克插混阵列里兼顾智能、空间和设计感的主力 SUV",
    recommendation: "适合接受插混、想要科技感和家用空间兼顾的用户",
    tags: ["technology", "family"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "smart_features", 9),
      weight("VEHICLE_PREFERENCE", "design_presence", 7),
      weight("VEHICLE_PREFERENCE", "comfort_space", 7),
      weight("PERSONALITY_TRAIT", "novelty_seeking", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("energy_acceptance_phev", "GTE", 2),
      constraint("family_size", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "lynkco-z10",
    brand: "领克",
    series: "Z10",
    modelName: "后驱智驾版",
    priceMin: 208800,
    priceMax: 288800,
    energyType: "EV",
    bodyType: "Sedan",
    summary: "领克纯电序列里更强调科技和运动表达的轿车",
    recommendation: "适合喜欢科技配置、外形张力和纯电性能的用户",
    tags: ["technology", "driving"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "smart_features", 9),
      weight("VEHICLE_PREFERENCE", "driving_engagement", 8),
      weight("VEHICLE_PREFERENCE", "design_presence", 8),
      weight("PERSONALITY_TRAIT", "expression_drive", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("charging_access", "GTE", 3),
      constraint("energy_acceptance_ev", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "lynkco-900",
    brand: "领克",
    series: "900",
    modelName: "EM-P",
    priceMin: 339900,
    priceMax: 419900,
    energyType: "PHEV",
    bodyType: "SUV",
    summary: "领克更高定位的大尺寸插混 SUV",
    recommendation: "适合预算充足、家庭成员多、又不想放弃设计和智能体验的用户",
    tags: ["family", "premium"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "family_fit", 9),
      weight("VEHICLE_PREFERENCE", "comfort_space", 9),
      weight("VEHICLE_PREFERENCE", "smart_features", 8),
      weight("PERSONALITY_TRAIT", "expression_drive", 5),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 5),
      constraint("family_size", "GTE", 3),
      constraint("energy_acceptance_phev", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "lynkco-01",
    brand: "领克",
    series: "01",
    modelName: "2.0TD",
    priceMin: 155800,
    priceMax: 196800,
    energyType: "ICE",
    bodyType: "SUV",
    summary: "领克燃油 SUV 里较均衡的经典车系",
    recommendation: "适合喜欢设计调性、又不想上新能源的用户",
    tags: ["balanced", "expression"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "design_presence", 8),
      weight("VEHICLE_PREFERENCE", "driving_engagement", 8),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 5),
      weight("PERSONALITY_TRAIT", "expression_drive", 5),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 3),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("family_size", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "lynkco-05-plus",
    brand: "领克",
    series: "05+",
    modelName: "性能套件版",
    priceMin: 236800,
    priceMax: 269800,
    energyType: "ICE",
    bodyType: "SUV",
    summary: "更偏个性轿跑姿态和性能表达的领克 SUV",
    recommendation: "适合在意造型、操控和个性标签的用户",
    tags: ["driving", "expression"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "design_presence", 8),
      weight("VEHICLE_PREFERENCE", "driving_engagement", 8),
      weight("VEHICLE_PREFERENCE", "brand_expression", 7),
      weight("PERSONALITY_TRAIT", "expression_drive", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("parking_constraint", "LTE", 4),
    ],
  }),
  vehicle({
    slug: "lynkco-06-emp",
    brand: "领克",
    series: "06 EM-P",
    modelName: "126 长续航 Max",
    priceMin: 136800,
    priceMax: 156800,
    energyType: "PHEV",
    bodyType: "SUV",
    summary: "更偏城市代步和年轻设计感的小型插混 SUV",
    recommendation: "适合城市场景、预算中等、愿意接受插混的年轻用户",
    tags: ["commute", "technology"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "smart_features", 8),
      weight("VEHICLE_PREFERENCE", "design_presence", 6),
      weight("VEHICLE_PREFERENCE", "running_cost", 7),
      weight("PERSONALITY_TRAIT", "novelty_seeking", 5),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 2),
      constraint("energy_acceptance_phev", "GTE", 2),
      constraint("parking_constraint", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "lynkco-07-emp",
    brand: "领克",
    series: "07 EM-P",
    modelName: "126 长续航 Halo",
    priceMin: 169800,
    priceMax: 189800,
    energyType: "PHEV",
    bodyType: "Sedan",
    summary: "年轻化插混轿车，兼顾设计、科技和成本",
    recommendation: "适合在意科技和设计，但又关注成本效率的用户",
    tags: ["technology", "expression"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "smart_features", 8),
      weight("VEHICLE_PREFERENCE", "design_presence", 7),
      weight("VEHICLE_PREFERENCE", "running_cost", 7),
      weight("PERSONALITY_TRAIT", "novelty_seeking", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 3),
      constraint("energy_acceptance_phev", "GTE", 2),
      constraint("intercity_highway_usage", "GTE", 1),
    ],
  }),
  vehicle({
    slug: "lynkco-09-emp",
    brand: "领克",
    series: "09 EM-P",
    modelName: "四驱 Ultra",
    priceMin: 307800,
    priceMax: 347800,
    energyType: "PHEV",
    bodyType: "SUV",
    summary: "大空间、长途能力和智能配置都更全面的插混 SUV",
    recommendation: "适合长途家庭场景、高预算和插混接受度较高的用户",
    tags: ["family", "technology"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "comfort_space", 8),
      weight("VEHICLE_PREFERENCE", "family_fit", 8),
      weight("VEHICLE_PREFERENCE", "smart_features", 8),
      weight("PERSONALITY_TRAIT", "planning_bias", 5),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 5),
      constraint("long_distance_frequency", "GTE", 2),
      constraint("energy_acceptance_phev", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "lynkco-z20",
    brand: "领克",
    series: "Z20",
    modelName: "后驱版",
    priceMin: 139800,
    priceMax: 159800,
    energyType: "EV",
    bodyType: "SUV",
    summary: "领克纯电入门序列里更偏年轻城市的车型",
    recommendation: "适合预算适中、有补能条件、偏爱年轻设计的用户",
    tags: ["ev", "expression"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "smart_features", 8),
      weight("VEHICLE_PREFERENCE", "design_presence", 8),
      weight("VEHICLE_PREFERENCE", "running_cost", 7),
      weight("PERSONALITY_TRAIT", "novelty_seeking", 5),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 2),
      constraint("charging_access", "GTE", 3),
      constraint("energy_acceptance_ev", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "lynkco-10-emp",
    brand: "领克",
    series: "10 EM-P",
    modelName: "四驱探索版",
    priceMin: 198800,
    priceMax: 239800,
    energyType: "PHEV",
    bodyType: "SUV",
    summary: "领克插混序列里更偏综合平衡的新 SUV",
    recommendation: "适合既想要科技和空间，又想控制补能焦虑的用户",
    tags: ["technology", "family"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "smart_features", 8),
      weight("VEHICLE_PREFERENCE", "comfort_space", 7),
      weight("VEHICLE_PREFERENCE", "driving_engagement", 6),
      weight("PERSONALITY_TRAIT", "novelty_seeking", 5),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("energy_acceptance_phev", "GTE", 2),
      constraint("family_size", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "tesla-model-y",
    brand: "特斯拉",
    series: "Model Y",
    modelName: "后轮驱动版",
    priceMin: 249900,
    priceMax: 354900,
    energyType: "EV",
    bodyType: "SUV",
    summary: "空间、智能体验和品牌认知都较强的纯电 SUV",
    recommendation: "适合有补能条件、既想要智能体验又想兼顾家用空间的用户",
    tags: ["technology", "family"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "smart_features", 9),
      weight("VEHICLE_PREFERENCE", "family_fit", 8),
      weight("VEHICLE_PREFERENCE", "brand_expression", 8),
      weight("PERSONALITY_TRAIT", "novelty_seeking", 7),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("charging_access", "GTE", 3),
      constraint("energy_acceptance_ev", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "xiaomi-yu7",
    brand: "小米",
    series: "YU7",
    modelName: "标准版",
    priceMin: 245900,
    priceMax: 329900,
    energyType: "EV",
    bodyType: "SUV",
    summary: "延续小米智能生态和设计表达的中型纯电 SUV",
    recommendation: "适合看重车机生态、设计表达和新能源体验的用户",
    tags: ["technology", "expression"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "smart_features", 10),
      weight("VEHICLE_PREFERENCE", "design_presence", 8),
      weight("VEHICLE_PREFERENCE", "brand_expression", 7),
      weight("PERSONALITY_TRAIT", "novelty_seeking", 8),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("charging_access", "GTE", 3),
      constraint("energy_acceptance_ev", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "byd-han",
    brand: "比亚迪",
    series: "汉",
    modelName: "DM-i",
    priceMin: 169800,
    priceMax: 259800,
    energyType: "PHEV",
    bodyType: "Sedan",
    summary: "更偏中大型轿车体验的王朝旗舰序列",
    recommendation: "适合既想兼顾家用舒适，又在意体面感和综合成本的用户",
    tags: ["family", "premium"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "comfort_space", 8),
      weight("VEHICLE_PREFERENCE", "design_presence", 7),
      weight("VEHICLE_PREFERENCE", "running_cost", 7),
      weight("PERSONALITY_TRAIT", "stability_preference", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 3),
      constraint("energy_acceptance_phev", "GTE", 2),
      constraint("intercity_highway_usage", "GTE", 1),
    ],
  }),
  vehicle({
    slug: "byd-tang",
    brand: "比亚迪",
    series: "唐",
    modelName: "DM-p",
    priceMin: 249800,
    priceMax: 309800,
    energyType: "PHEV",
    bodyType: "SUV",
    summary: "大空间、多成员出行友好的中大型插混 SUV",
    recommendation: "适合家庭人口多、周末出行频繁且能接受插混方案的用户",
    tags: ["family", "technology"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "family_fit", 10),
      weight("VEHICLE_PREFERENCE", "comfort_space", 9),
      weight("VEHICLE_PREFERENCE", "smart_features", 7),
      weight("PERSONALITY_TRAIT", "planning_bias", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("family_size", "GTE", 3),
      constraint("energy_acceptance_phev", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "byd-yuan-plus",
    brand: "比亚迪",
    series: "元 PLUS",
    modelName: "冠军版",
    priceMin: 119800,
    priceMax: 163800,
    energyType: "EV",
    bodyType: "SUV",
    summary: "尺寸适中、城市代步友好的纯电 SUV",
    recommendation: "适合预算中等、有补能条件、兼顾家用和城市通勤的用户",
    tags: ["ev", "commute"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "running_cost", 8),
      weight("VEHICLE_PREFERENCE", "family_fit", 7),
      weight("VEHICLE_PREFERENCE", "smart_features", 6),
      weight("PERSONALITY_TRAIT", "cost_control", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 2),
      constraint("charging_access", "GTE", 3),
      constraint("energy_acceptance_ev", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "geely-xingrui",
    brand: "吉利",
    series: "星瑞",
    modelName: "2.0TD",
    priceMin: 108700,
    priceMax: 146700,
    energyType: "ICE",
    bodyType: "Sedan",
    summary: "配置、空间和性价比都比较均衡的燃油轿车",
    recommendation: "适合预算理性、偏传统动力、同时希望配置不差的用户",
    tags: ["value", "commute"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "running_cost", 8),
      weight("VEHICLE_PREFERENCE", "comfort_space", 8),
      weight("VEHICLE_PREFERENCE", "design_presence", 6),
      weight("PERSONALITY_TRAIT", "cost_control", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 2),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("monthly_payment_sensitivity", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "geely-galaxy-e5",
    brand: "吉利银河",
    series: "E5",
    modelName: "530km",
    priceMin: 109800,
    priceMax: 145800,
    energyType: "EV",
    bodyType: "SUV",
    summary: "更偏家庭和通勤平衡的纯电 SUV",
    recommendation: "适合预算有限但仍然想要新能源家用 SUV 的用户",
    tags: ["ev", "family"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "family_fit", 7),
      weight("VEHICLE_PREFERENCE", "running_cost", 8),
      weight("VEHICLE_PREFERENCE", "smart_features", 6),
      weight("PERSONALITY_TRAIT", "cost_control", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 2),
      constraint("charging_access", "GTE", 3),
      constraint("energy_acceptance_ev", "GTE", 3),
    ],
  }),
  vehicle({
    slug: "geely-galaxy-l7",
    brand: "吉利银河",
    series: "L7",
    modelName: "EM-i",
    priceMin: 129800,
    priceMax: 169800,
    energyType: "PHEV",
    bodyType: "SUV",
    summary: "主打成本效率和智能配置的插混家用 SUV",
    recommendation: "适合家庭导向明显、又在意智能和通勤成本的用户",
    tags: ["family", "technology"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "family_fit", 8),
      weight("VEHICLE_PREFERENCE", "smart_features", 7),
      weight("VEHICLE_PREFERENCE", "running_cost", 8),
      weight("PERSONALITY_TRAIT", "planning_bias", 5),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 2),
      constraint("energy_acceptance_phev", "GTE", 2),
      constraint("family_size", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "volkswagen-magotan",
    brand: "大众",
    series: "迈腾",
    modelName: "380TSI",
    priceMin: 179900,
    priceMax: 249900,
    energyType: "ICE",
    bodyType: "Sedan",
    summary: "经典中型轿车路线下更偏均衡和成熟的一台车",
    recommendation: "适合务实、通勤和长途兼顾、希望选择成熟车型的用户",
    tags: ["reliable", "commute"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "daily_reliability", 8),
      weight("VEHICLE_PREFERENCE", "comfort_space", 7),
      weight("VEHICLE_PREFERENCE", "simplicity_reliability", 7),
      weight("PERSONALITY_TRAIT", "stability_preference", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 3),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("resale_sensitivity", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "volkswagen-tayron",
    brand: "大众",
    series: "探岳",
    modelName: "330TSI",
    priceMin: 186900,
    priceMax: 256900,
    energyType: "ICE",
    bodyType: "SUV",
    summary: "空间和品牌成熟度都在线的中型燃油 SUV",
    recommendation: "适合偏传统动力、家用空间需求明确的用户",
    tags: ["family", "reliable"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "family_fit", 8),
      weight("VEHICLE_PREFERENCE", "comfort_space", 8),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 7),
      weight("PERSONALITY_TRAIT", "planning_bias", 5),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 3),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("family_size", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "toyota-camry",
    brand: "丰田",
    series: "凯美瑞",
    modelName: "双擎",
    priceMin: 171800,
    priceMax: 259800,
    energyType: "HEV",
    bodyType: "Sedan",
    summary: "更偏长期持有和综合稳定性的主流中型轿车",
    recommendation: "适合看重可靠性、保值和通勤舒适度的用户",
    tags: ["reliable", "commute"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "daily_reliability", 10),
      weight("VEHICLE_PREFERENCE", "running_cost", 8),
      weight("VEHICLE_PREFERENCE", "comfort_space", 7),
      weight("PERSONALITY_TRAIT", "stability_preference", 7),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 3),
      constraint("resale_sensitivity", "GTE", 2),
      constraint("intercity_highway_usage", "GTE", 1),
    ],
  }),
  vehicle({
    slug: "toyota-highlander",
    brand: "丰田",
    series: "汉兰达",
    modelName: "双擎",
    priceMin: 284800,
    priceMax: 348800,
    energyType: "HEV",
    bodyType: "SUV",
    summary: "七座家用和长途出行场景里较成熟的混动 SUV",
    recommendation: "适合大家庭、多人口出行和长途场景较多的用户",
    tags: ["family", "reliable"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "family_fit", 10),
      weight("VEHICLE_PREFERENCE", "comfort_space", 9),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 9),
      weight("PERSONALITY_TRAIT", "planning_bias", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 4),
      constraint("family_size", "GTE", 3),
      constraint("full_load_frequency", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "honda-civic",
    brand: "本田",
    series: "思域",
    modelName: "240TURBO",
    priceMin: 129900,
    priceMax: 187900,
    energyType: "ICE",
    bodyType: "Sedan",
    summary: "兼顾年轻化操控感和日常可用性的紧凑级轿车",
    recommendation: "适合预算中等、希望通勤之外保留一些驾驶乐趣的用户",
    tags: ["driving", "commute"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "driving_engagement", 8),
      weight("VEHICLE_PREFERENCE", "simplicity_reliability", 7),
      weight("VEHICLE_PREFERENCE", "design_presence", 6),
      weight("PERSONALITY_TRAIT", "control_preference", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 2),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("parking_constraint", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "honda-hrv",
    brand: "本田",
    series: "HR-V",
    modelName: "e:HEV",
    priceMin: 159900,
    priceMax: 199900,
    energyType: "HEV",
    bodyType: "SUV",
    summary: "更偏城市家用的小型混动 SUV",
    recommendation: "适合空间需求适中、停车压力存在、又想兼顾经济性的用户",
    tags: ["commute", "family"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "running_cost", 8),
      weight("VEHICLE_PREFERENCE", "family_fit", 6),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 7),
      weight("PERSONALITY_TRAIT", "cost_control", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 3),
      constraint("parking_constraint", "GTE", 3),
      constraint("energy_acceptance_phev", "GTE", 1),
    ],
  }),
  vehicle({
    slug: "bmw-3-series",
    brand: "宝马",
    series: "3 系",
    modelName: "325Li",
    priceMin: 299900,
    priceMax: 399900,
    energyType: "ICE",
    bodyType: "Sedan",
    summary: "品牌感和后驱驾驶质感更鲜明的豪华中型轿车",
    recommendation: "适合预算较高、看重品牌和驾控反馈的用户",
    tags: ["premium", "driving"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "driving_engagement", 9),
      weight("VEHICLE_PREFERENCE", "brand_expression", 9),
      weight("VEHICLE_PREFERENCE", "design_presence", 7),
      weight("PERSONALITY_TRAIT", "expression_drive", 7),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 5),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("monthly_payment_sensitivity", "LTE", 3),
    ],
  }),
  vehicle({
    slug: "bmw-x3",
    brand: "宝马",
    series: "X3",
    modelName: "xDrive30i",
    priceMin: 399600,
    priceMax: 489600,
    energyType: "ICE",
    bodyType: "SUV",
    summary: "豪华品牌里兼顾空间和驾控的中型 SUV",
    recommendation: "适合既想要品牌感和空间，又不愿放弃驾驶感的用户",
    tags: ["premium", "family"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "brand_expression", 9),
      weight("VEHICLE_PREFERENCE", "driving_engagement", 8),
      weight("VEHICLE_PREFERENCE", "comfort_space", 7),
      weight("PERSONALITY_TRAIT", "control_preference", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 5),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("family_size", "GTE", 2),
    ],
  }),
  vehicle({
    slug: "mercedes-glc",
    brand: "奔驰",
    series: "GLC",
    modelName: "260 L",
    priceMin: 427800,
    priceMax: 531300,
    energyType: "ICE",
    bodyType: "SUV",
    summary: "豪华氛围、空间和品牌认知都很强的中型 SUV",
    recommendation: "适合预算充足、重视体面感和舒适性的用户",
    tags: ["premium", "family"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "brand_expression", 10),
      weight("VEHICLE_PREFERENCE", "comfort_space", 8),
      weight("VEHICLE_PREFERENCE", "design_presence", 8),
      weight("PERSONALITY_TRAIT", "expression_drive", 6),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 5),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("monthly_payment_sensitivity", "LTE", 3),
    ],
  }),
  vehicle({
    slug: "audi-a4l",
    brand: "奥迪",
    series: "A4L",
    modelName: "40TFSI",
    priceMin: 321800,
    priceMax: 405800,
    energyType: "ICE",
    bodyType: "Sedan",
    summary: "豪华品牌轿车里更偏均衡和理性的选择",
    recommendation: "适合想要豪华品牌，但也在意长期通勤和综合平衡的用户",
    tags: ["premium", "reliable"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "brand_expression", 8),
      weight("VEHICLE_PREFERENCE", "daily_reliability", 6),
      weight("VEHICLE_PREFERENCE", "comfort_space", 7),
      weight("PERSONALITY_TRAIT", "planning_bias", 5),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 5),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("monthly_payment_sensitivity", "LTE", 3),
    ],
  }),
  vehicle({
    slug: "audi-q5l",
    brand: "奥迪",
    series: "Q5L",
    modelName: "45TFSI",
    priceMin: 395800,
    priceMax: 488800,
    energyType: "ICE",
    bodyType: "SUV",
    summary: "兼顾品牌、空间和综合豪华感的中型 SUV",
    recommendation: "适合家庭需求明确，同时希望保留豪华品牌认知的用户",
    tags: ["premium", "family"],
    traitWeights: [
      weight("VEHICLE_PREFERENCE", "brand_expression", 8),
      weight("VEHICLE_PREFERENCE", "family_fit", 7),
      weight("VEHICLE_PREFERENCE", "comfort_space", 7),
      weight("PERSONALITY_TRAIT", "stability_preference", 5),
    ],
    constraintRules: [
      constraint("budget_level", "GTE", 5),
      constraint("energy_acceptance_ice", "GTE", 3),
      constraint("family_size", "GTE", 2),
    ],
  }),
] as const;
